### ISSUE TITLE
Wrong SP Identity Store bean name getting generated.

### ISSUE THREAD

**Issue by arijeetsaha** [atricore/josso2#1]
When deploying the Identity appliance, wrong the SP bean name is getting generated in the xml file. The identitystore bean for the Service Provider 'SP1' should be 'dbsource1-identity-store' instead it is generated as 'sp1-identity-store' using the bean id of SP.

Please refer the configuration diagram and the error logs below:

Below diagram shows the configuration:
![screen shot 2015-06-28 at 8 48 22 pm](https://cloud.githubusercontent.com/assets/13103538/8409625/c921e3f4-1e96-11e5-8f3c-f1ae1be4d3e1.png)

Logs:

2015-06-28 20:29:48,625 | ERROR | qtp-903957533-16 | IdentityServiceBootstrap | ervices.IdentityServiceBootstrap 62 | 166 - org.atricore.idbus.kernel.common.support - 1.4.0 | Spring Application context in Bundle (260) com.sso.josso2.demo.ida1.idappliance1.idau : FAILED 2015-06-28 20:29:48,625 | ERROR | qtp-903957533-16 | ServicesLifecycleManager | in.boot.ServicesLifecycleManager 61 | 233 - com.atricore.idbus.console.lifecycle.main - 1.3.0 | Spring Application context in Bundle (260) com.sso.josso2.demo.ida1.idappliance1.idau : FAILED 2015-06-28 20:29:48,625 | ERROR | qtp-903957533-16 | ContextLoaderListener | BundleApplicationContextListener 50 | 54 - org.springframework.osgi.extender - 1.2.1 | Application context refresh failed (OsgiBundleXmlApplicationContext(bundle=com.sso.josso2.demo.ida1.idappliance1.idau, config=osgibundle:/META-INF/spring/_.xml)) Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named_  **'sp1-identity-store'** is defined at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:529) at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1095) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)

**Comment by sgonzalezoyuela** [comment]
Solved in update
