### ISSUE TITLE
LifecycleException:  Error starting SSO Agent : Unexpected exception parsing XML document from class path resource [josso-agent-config.xml]

### ISSUE THREAD

**Issue by Naresh1080** [atricore/josso2#3]
I am using Java-7, tomcat-6, Josso-1.8.10.
After configuring JOSSO gateway and agent, I started the tomcat but got below exception, 

---

INFO: Starting service Catalina
Jan 19, 2016 11:55:38 AM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.43
Jan 19, 2016 11:55:38 AM org.josso.agent.Lookup init
INFO: Init resourceName <josso-agent-config.xml>
Jan 19, 2016 11:55:39 AM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.apache.xbean.spring.context.ClassPathXmlApplicationContext@1110fa8: display name [org.apache.xbean.spring.context.ClassPathXmlApplicationContext@1110fa8]; startup date [Tue Jan 19 11:55:39 IST 2016]; root of context hierarchy
Jan 19, 2016 11:55:39 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [josso-agent-config.xml]
Jan 19, 2016 11:55:39 AM org.apache.catalina.startup.Catalina start
SEVERE: Catalina.start: 
LifecycleException:  Error starting SSO Agent : Unexpected exception parsing XML document from class path resource [josso-agent-config.xml]; nested exception is java.lang.NullPointerException
    at org.josso.tc60.agent.SSOAgentValve.start(SSOAgentValve.java:216)
    at org.apache.catalina.core.StandardPipeline.start(StandardPipeline.java:233)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1060)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
    at org.apache.catalina.core.StandardService.start(StandardService.java:525)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:759)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Jan 19, 2016 11:55:39 AM org.apache.catalina.startup.Catalina start
## INFO: Server startup in 323 ms

Could you please support/suggest us in resolving the issue?

Regards,
Naresh

**Comment by sgonzalezoyuela** [comment]
solved in update #3
