### ISSUE TITLE
JDBC connection issue in Josso2 after upgrading to oracle 18c

### ISSUE THREAD

**Issue by pratikthaker84** [atricore/josso2#6]
We are trying to use Josso2 2.4.3 (installed by josso-ce-2.4.3-34-windows.jar) with oracle 18c. That means we have copied ojdbc8.jar to josso2/lib/jdbc folder We are using it with apache tomcat 8.0.27

We have provided connection parameters and authentication queries to the appliance added using josso UI.

But whenever user it trying to login, we are getting below exception in atricore.log

`java.lang.NoClassDefFoundError: javax/security/auth/login/Configuration
        at java.lang.Class.forName0(Native Method)[:1.8.0_60]
        at java.lang.Class.forName(Class.java:264)[:1.8.0_60]
        at oracle.net.ano.Ano.init(Unknown Source)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:311)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1481)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:540)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:782)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:704)
        at org.atricore.idbus.kernel.common.support.jdbc.JDBCDriverManager$WrappedDriver.connect(JDBCDriverManager.java:461)[180:org.atricore.idbus.kernel.common.support:1.4.3.SNAPSHOT]
        at java.sql.DriverManager.getConnection(DriverManager.java:664)[:1.8.0_60]
        at java.sql.DriverManager.getConnection(DriverManager.java:208)[:1.8.0_60]
        at org.atricore.idbus.kernel.common.support.jdbc.JDBCDriverManager.doConnect(JDBCDriverManager.java:207)[180:org.atricore.idbus.kernel.common.support:1.4.3.SNAPSHOT]
        at org.atricore.idbus.kernel.common.support.jdbc.JDBCDriverManager.getConnection(JDBCDriverManager.java:164)[180:org.atricore.idbus.kernel.common.support:1.4.3.SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)`

**Comment by sgonzalezoyuela** [comment]
updated in latest version
